services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    build: .
    command: sh -c "alembic upgrade head && python3 main.py"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
